### PR TITLE
 Add bidirectional support for Scene Item Visibility

### PR DESCRIPTION
**Pull request by spessoni**
I needed to be able to visually see if scene items where visible or not.  This can be helpful for building AUX buses and DSK's (Down Stream Keyer). The bidirectional support works well when scenes are specified, but can become out of sync if selecting "--Current--". This would require requesting the visibility status on every scene change. I also almost exclusively use this in "Studio Mode".

- Added support for bidirectional for Scene Item Viability
- Added settings in setup.py to enable bidirectional support
- Fixed some spelling typos in README.md
- Added how to manually check which MIDI device are available with python to README.md
- Added TYST TY-1500HD Switcher to "tested with" in README.md

### CODE REVIEW

**Comment by spessoni** [comment]
I need to figure out how to Squash Commits

**Comment by lebaston100** [comment]
Thanks for this contribution. This will need some deeper testing on my end which will take some time due to the current lack of midi hardware. No ETA on a merge.

**Comment by spessoni** [comment]
No problem. There are some software based MIDI control surfaces you may be able to use for testing.  I know Android even has some WiFi based apps.

Do I need to attempt to squash this? Or is that something you can do while merging? (This is my first PR)

**Comment by lebaston100** [comment]
Yea, i've just remembered that my stream deck has midi support which i have all setup, so no worries. Still can't guarantee when i'll merge. There is the obs-websocket 5.0 release not too far away which will require a massive rework, so i hope i can get this merged before doing all that work.
Don't bother with squashing, github has an option to automatically do that when pressing the merge button.

**Review by lebaston100 — APPROVED** [review]
The scene name seems like it's not used besides for debug logging and breaks the program when "current scene" is used in the setup instead of a specific scene. I'll fix this myself after merging.

**Pull request merged**
