### PR TITLE
Bidirectional MIDI controls

### PR DESCRIPTION
**Pull request by houz**
Hello,

this PR adds support for reacting to OBS messages and sending MIDI messages. Currently it only reacts to changes of the scene (current and preview), but adding other feedback should be easy.

I also fixed some bugs in the registration of WebSocketApp callbacks.

I tested this with a KORG nanoKONTROL2.

Related to issue #16 .

### CODE REVIEW

**Comment by lebaston100** [comment]
Looks fine to me.
I'm actually amazed that you can send to an input port. I've looked though the ports documentation a few times and it's never clearly mentioned that it does.
Also i can't test it as mentioned in the issue, still lacking the hardware.
I will give your branch a test if anything broke for non-bidirectional devices but other then that i'll merge that in the near future.

**Comment by houz** [comment]
Thank you. I don't think you can send to an input port, that's why I changed it to an io port.

**Comment by lebaston100** [comment]
Oh right, i apparently missed that while reading though it.

**Comment by me-vlad** [comment]
Hi,
Changing mido.open_input to mido.open_ioport without checking device compatibility will cause connect issues like with my Behringer X-Touch Mini

```python
Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mido
>>> mido.get_ioport_names()
[]
>>> mido.get_input_names()
['X-TOUCH MINI 0'] 
>>> mido.get_output_names()
['Microsoft GS Wavetable Synth 0', 'X-TOUCH MINI 1'] 
>>>
```

```
C:\Users\Vlad\Desktop\MIDItoOBS-bidirectional>python main.py
[2020-04-10 13:20:45,935] (INFO) T8960 : Successfully parsed config file
--- Logging error --- 
Traceback (most recent call last):
  File "main.py", line 76, in __init__
    self._port = mido.open_ioport(name=self._devicename, callback=self.callback, autoreset=True)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\backends\backend.py", line 159, in open_ioport
    self.module.Output(output_name, **kwargs))
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\ports.py", line 265, in __init__
    BasePort.__init__(self, name, **kwargs)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\ports.py", line 86, in __init__
    self._open(**kwargs)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\backends\rtmidi.py", line 190, in _open
    virtual=virtual, api=self.api)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\backends\rtmidi.py", line 93, in _open_port
    raise IOError('unknown port {!r}'.format(name))
OSError: unknown port 'X-TOUCH MINI 0'
```

**Comment by lebaston100** [comment]
Thanks for testing that @me-vlad .
I though that might happen that's why i said i need to test it first with a unidirectional device before merging.
Best case i think would be to add a flag into the device object inside the database itself that indicates that it supports receiving too and then use that information in the DeviceHandler __init__ before opening the device.
Otherwise we could just try with ioport first and in case that goes into the except try again with only input device.
I wonder why the try except doesn't catch that exception.

**Comment by me-vlad** [comment]
Full output

```
C:\Users\Vlad\Desktop\MIDItoOBS-bidirectional>python main.py
[2020-04-10 13:20:45,935] (INFO) T8960 : Successfully parsed config file
--- Logging error --- 
Traceback (most recent call last):
  File "main.py", line 76, in __init__
    self._port = mido.open_ioport(name=self._devicename, callback=self.callback, autoreset=True)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\backends\backend.py", line 159, in open_ioport
    self.module.Output(output_name, **kwargs))
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\ports.py", line 265, in __init__
    BasePort.__init__(self, name, **kwargs)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\ports.py", line 86, in __init__
    self._open(**kwargs)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\backends\rtmidi.py", line 190, in _open
    virtual=virtual, api=self.api)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\backends\rtmidi.py", line 93, in _open_port
    raise IOError('unknown port {!r}'.format(name))
OSError: unknown port 'X-TOUCH MINI 0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "main.py", line 388, in <module>
    handler = MidiHandler()
  File "main.py", line 139, in __init__
    self._portobjects.append((DeviceHandler(device, device.doc_id), device.doc_id))
  File "main.py", line 78, in __init__
    self.log.critical("\nCould not open", self._devicename)
Message: '\nCould not open'
Arguments: ('X-TOUCH MINI 0',)
--- Logging error ---
Traceback (most recent call last):
  File "main.py", line 76, in __init__
    self._port = mido.open_ioport(name=self._devicename, callback=self.callback, autoreset=True)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\backends\backend.py", line 159, in open_ioport
    self.module.Output(output_name, **kwargs))
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\ports.py", line 265, in __init__
    BasePort.__init__(self, name, **kwargs)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\ports.py", line 86, in __init__
    self._open(**kwargs)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\backends\rtmidi.py", line 190, in _open
    virtual=virtual, api=self.api)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\backends\rtmidi.py", line 93, in _open_port
    raise IOError('unknown port {!r}'.format(name))
OSError: unknown port 'X-TOUCH MINI 0'

Traceback (most recent call last):
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "main.py", line 388, in <module>
    handler = MidiHandler()
  File "main.py", line 139, in __init__
    self._portobjects.append((DeviceHandler(device, device.doc_id), device.doc_id))
  File "main.py", line 78, in __init__
    self.log.critical("\nCould not open", self._devicename)
Message: '\nCould not open'
Arguments: ('X-TOUCH MINI 0',)
[2020-04-10 13:20:45,976] (CRITICAL) T8960 : The midi device might be used by another application/not plugged in/have a different name.
[2020-04-10 13:20:45,977] (CRITICAL) T8960 : Please close the device in the other application/plug it in/select the rename option in the device management menu and restart this script.
```

**Comment by cpyarger** [comment]
I had a similar issue with opening an IO port regarding my x touch
compact.  even though it should work bi-directionally.
Warmest Regards,


Christopher P. Yarger

Phone: 802-505-7574
Skype: cpyarger

/************************************
Based upon email reliability concerns,
please send an acknowledgment in response to this note.

**Comment by lebaston100** [comment]
> Full output
> 
> ```
> C:\Users\Vlad\Desktop\MIDItoOBS-bidirectional>python main.py
> [2020-04-10 13:20:45,935] (INFO) T8960 : Successfully parsed config file
> --- Logging error --- 
> Traceback (most recent call last):
>   File "main.py", line 76, in __init__
>     self._port = mido.open_ioport(name=self._devicename, callback=self.callback, autoreset=True)
>   File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\backends\backend.py", line 159, in open_ioport
>     self.module.Output(output_name, **kwargs))
>   File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\ports.py", line 265, in __init__
>     BasePort.__init__(self, name, **kwargs)
>   File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\ports.py", line 86, in __init__
>     self._open(**kwargs)
>   File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\backends\rtmidi.py", line 190, in _open
>     virtual=virtual, api=self.api)
>   File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\backends\rtmidi.py", line 93, in _open_port
>     raise IOError('unknown port {!r}'.format(name))
> OSError: unknown port 'X-TOUCH MINI 0'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1025, in emit
>     msg = self.format(record)
>   File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 869, in format
>     return fmt.format(record)
>   File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 608, in format
>     record.message = record.getMessage()
>   File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 369, in getMessage
>     msg = msg % self.args
> TypeError: not all arguments converted during string formatting
> Call stack:
>   File "main.py", line 388, in <module>
>     handler = MidiHandler()
>   File "main.py", line 139, in __init__
>     self._portobjects.append((DeviceHandler(device, device.doc_id), device.doc_id))
>   File "main.py", line 78, in __init__
>     self.log.critical("\nCould not open", self._devicename)
> Message: '\nCould not open'
> Arguments: ('X-TOUCH MINI 0',)
> --- Logging error ---
> Traceback (most recent call last):
>   File "main.py", line 76, in __init__
>     self._port = mido.open_ioport(name=self._devicename, callback=self.callback, autoreset=True)
>   File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\backends\backend.py", line 159, in open_ioport
>     self.module.Output(output_name, **kwargs))
>   File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\ports.py", line 265, in __init__
>     BasePort.__init__(self, name, **kwargs)
>   File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\ports.py", line 86, in __init__
>     self._open(**kwargs)
>   File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\backends\rtmidi.py", line 190, in _open
>     virtual=virtual, api=self.api)
>   File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\backends\rtmidi.py", line 93, in _open_port
>     raise IOError('unknown port {!r}'.format(name))
> OSError: unknown port 'X-TOUCH MINI 0'
> 
> Traceback (most recent call last):
>   File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1025, in emit
>     msg = self.format(record)
>   File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 869, in format
>     return fmt.format(record)
>   File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 608, in format
>     record.message = record.getMessage()
>   File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 369, in getMessage
>     msg = msg % self.args
> TypeError: not all arguments converted during string formatting
> Call stack:
>   File "main.py", line 388, in <module>
>     handler = MidiHandler()
>   File "main.py", line 139, in __init__
>     self._portobjects.append((DeviceHandler(device, device.doc_id), device.doc_id))
>   File "main.py", line 78, in __init__
>     self.log.critical("\nCould not open", self._devicename)
> Message: '\nCould not open'
> Arguments: ('X-TOUCH MINI 0',)
> [2020-04-10 13:20:45,976] (CRITICAL) T8960 : The midi device might be used by another application/not plugged in/have a different name.
> [2020-04-10 13:20:45,977] (CRITICAL) T8960 : Please close the device in the other application/plug it in/select the rename option in the device management menu and restart this script.
> ```

Well, that should now be fixed with https://github.com/lebaston100/MIDItoOBS/commit/ae6de7f1018c50d0170aacd06baa7b9bc65f0292

**Comment by houz** [comment]
Thanks for your feedback. I added a check if the device is capable to do IO. Of course, that will still fail if the device lies and isn't actually supporting it. I am not sure if that is the case with the X-Touch Mini.

**Comment by me-vlad** [comment]
> Edit: Actually, I just noticed that there are 2 X-Touch Mini reported, one for input and one for output. I assume that's the same physical device though?

Yes it is the same device listed in input and output devices but not in ioport list

**Comment by houz** [comment]
I tried to fix the case that different logical midi devices are needed for input and output. You have to add the 2nd device in your config, and add a key `out_deviceID` to the key mapping, analogous to `deviceID`.

**Comment by me-vlad** [comment]
Hi Tobias, thanks for your help.
Just added manually to my config.json  my midi device as output,
It work fine as an input device (without errors in console) but leds on buttons not inicates preview/current scene.

My mido device names
```
>>> import mido
>>> mido.get_input_names()
['X-TOUCH MINI 0']
>>> mido.get_output_names()
['Microsoft GS Wavetable Synth 0', 'X-TOUCH MINI 1']
```

My test config (two buttons for "preview" and two another - for "program")

```json
{
    "_default": {},
    "keys": {
        "1": {
            "msg_type": "note_on",
            "msgNoC": 16,
            "input_type": "button",
            "action": "{\"request-type\": \"SetPreviewScene\", \"message-id\" : \"1\",\"scene-name\" : \"CAMERA1 - 1\"}",
            "deviceID": 1,
            "out_deviceID": 2,
            "bidirectional": true
        },
        "2": {
            "msg_type": "note_on",
            "msgNoC": 17,
            "input_type": "button",
            "action": "{\"request-type\": \"SetPreviewScene\", \"message-id\" : \"1\",\"scene-name\" : \"CAMERA2 - 2\"}",
            "deviceID": 1,
            "out_deviceID": 2,
            "bidirectional": true
        },
        "3": {
            "msg_type": "note_on",
            "msgNoC": 8,
            "input_type": "button",
            "action": "{\"request-type\": \"SetCurrentScene\", \"message-id\" : \"1\", \"scene-name\" : \"CAMERA1 - 1\"}",
            "deviceID": 1,
            "out_deviceID": 2,
            "bidirectional": true
        },
        "4": {
            "msg_type": "note_on",
            "msgNoC": 9,
            "input_type": "button",
            "action": "{\"request-type\": \"SetCurrentScene\", \"message-id\" : \"1\", \"scene-name\" : \"CAMERA2 - 2\"}",
            "deviceID": 1,
            "out_deviceID": 2,
            "bidirectional": true
        }
    },
    "devices": {
        "1": {
            "devicename": "X-TOUCH MINI 0"
        },
        "2": {
            "devicename": "X-TOUCH MINI 1"
        }
    }
}
```

**Comment by houz** [comment]
Does the following code turn on a light?

```
import mido
port = mido.open_output('X-TOUCH MINI 1')
port.send(mido.Message(type="note_on", channel=0, control=8, value=127))
```

**Comment by me-vlad** [comment]
Xtouch Mini has 2 modes - standart midi (in this mode device works with miditoobs) and mackie control mode (MC). 

Buttons led in standart mode on my device turns on with
port.send(mido.Message(type="note_on", channel=0, note=8, velocity=1))
and turns off with
port.send(mido.Message(type="note_on", channel=0, note=8, velocity=0))


```
>>> port.send(mido.Message(type="note_on", channel=0, control=8, value=127))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\messages\messages.py", line 88, in __init__
    check_msgdict(msgdict)
  File "C:\Users\Vlad\AppData\Local\Programs\Python\Python37\lib\site-packages\mido\messages\checks.py", line 97, in check_msgdict
    '{} message has no attribute {}'.format(spec['type'], name))
ValueError: note_on message has no attribute control
>>>
>>>
>>> mido.Message('note_on')
<message note_on channel=0 note=0 velocity=64 time=0>
>>>
>>>
>>>
>>> # led on
... port.send(mido.Message(type="note_on", channel=0, note=8, velocity=1))
>>>
>>>
>>> # len off
... port.send(mido.Message(type="note_on", channel=0, note=8, velocity=0))
```

**Comment by houz** [comment]
Next round of testing. :-)

**Comment by me-vlad** [comment]
Thanks @houz ,
Just tested you branch and found one more nuance - buttons (notes) numbering for input and output device does not match. For example: input device configured by setyp.py with buttons from 8 to 23, in same time for output device buttons numbered from 0 to 15.
So, to flush button 8 I need to ineract with button 0 on the output device.
May be we need to add manually  not only out_deviceID but also something like out_msgNoC ?

**Comment by houz** [comment]
Thank you again for your feedback. I added `out_msgNoC`.

**Comment by me-vlad** [comment]
@houz, now it works after adding out_msgNoC to buttons config.
Minor issue - buttons led turns on not right after pressing a button to select scene, but only after scene transition (takes scene status info from OBS websocket?)

**Comment by houz** [comment]
Yes, that is on purpose as it makes the code easier – we have to react to scene change events from OBS anyway. Of course it wouldn't be hard to set it immediately when sending the command to OBS. The subsequent message received would just set it again.

**Comment by lebaston100** [comment]
I would leave it like this by design. What might be confusing at first is actually kind of handy and how i would expect it to work.
Right now it's listening to SwitchScenes and PreviewSceneChanged events. If you wanted to light up both buttons at the same time when using a transition that is not a cut, you would need to additionally listen to the TransitionBegin event.

**Comment by houz** [comment]
Reacting to `TransitionBegin` is easy of course, but what would be the right thing to show? Keeping the preview button unaffected and lighting both current scene buttons? This is one of those cases where finding a good design is way harder than writing the code.

**Comment by lebaston100** [comment]
So for traditional hardware video mixer that can display red and green the concept if simple: if a source is visible it's red. So when there is a transition the green instantly changes to red (so both buttons are red at that moment). And when the transition is done the now-preview scene changes to green.
That's exactly how it's implemented in https://github.com/lebaston100/OBS-to-XAir and https://github.com/lebaston100/OBSliveTally
But for the sake of simplicity here i suggest we just leave it how it is now.

**Comment by houz** [comment]
I don't really care, making both buttons light up while the transition happens would be easy. Tell me what you prefer as a user experience and I will implement it. I don't think simplicity of code should be the determining factor here. :smiley:

**Comment by cpyarger** [comment]
Little side question. Would it make sense to wrap the ports in a multiport.
That way you can get around the separate input and output ports for the
behringer devices?

**Comment by lebaston100** [comment]
For now i'm perfectly fine with it. From a UX side i don't really know which is right but i could imagine some confusion with the technical correct version. But on the other hand the entire script is tui-based so what do i know about UX :D 
This whole thing needs a complete rewrite anyway sometime in the very far future.
I'm thinking about having device template files that can be selected and loaded that define the midi values needed to light up the buttons or move faders. But that's just a potential idea.

**Comment by houz** [comment]
Good idea, having a description of a concrete device would even allow to write a gui that shows an image of the hardware with overlays in setup. Just thinking out loud here.

**Comment by lebaston100** [comment]
Yea exactly that's what i was thinking too. Having a online docs page for every device with a svg of the device with numbers that links to the right entry in the configuration file.

**Comment by me-vlad** [comment]
IMHO something like "device database" with tipical mapping for different hw models + ability to edit config file manually (for advanced users) - a good solution.

**Comment by houz** [comment]
I don't think those advanced features are in the scope of this PR. So, is there anything else I should do to get this merged?

**Comment by lebaston100** [comment]
No, nothing from your end. I wasn't expecting you to add all that stuff. Now it's my turn. Thanks again.

**Pull request merged**
